[tool.poetry]
name = "vector-db-example"
version = "0.2.2"
description = ""
authors = ["Peter <ppspot@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
psycopg2-binary = "^2.9.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
