[project]
name = "simple-database-connection-application"
version = "0.1.1"
requires-python = ">=3.9,<4"
readme = "readme.md"
authors = [
    { name = "Peter Paton", email = "abc@email.com" }
]

dependencies = [
    "psycopg2-binary==2.9.9"
]
